# Generated by Django 5.0.3 on 2024-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StallName', models.CharField(max_length=255)),
                ('SellerName', models.CharField(max_length=255)),
                ('ContactNo', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=64)),
            ],
        ),
    ]
