# Generated by Django 5.0.3 on 2024-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
