# Generated by Django 5.0.3 on 2024-03-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerregistration', '0002_alter_seller_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=255, unique=True)),
                ('ContactNo', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='seller',
            name='Username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
